/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\github\gorilla\nimcache\main.o d:\documents\projects\github\gorilla\nimcache\main.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct gaumanager95208 gaumanager95208;
typedef struct gamixer93343 gamixer93343;
typedef struct gaformat93178 gaformat93178;
typedef struct gclink93144 gclink93144;
typedef struct gcmutex92270 gcmutex92270;
typedef N_CDECL_PTR(gaumanager95208*, TY95225) (NI32 indevtype, NI32 inthreadpolicy, NI32 innumbuffers, NI32 inbuffersamples);
typedef N_CDECL_PTR(gamixer93343*, TY95242) (gaumanager95208* inmgr);
struct  gaumanager95208  {
char dummy;
};
struct  gaformat93178  {
NI32 Samplerate;
NI32 Bitspersample;
NI32 Numchannels;
};
struct  gclink93144  {
gclink93144* Next;
gclink93144* Prev;
void* Data;
};
struct  gamixer93343  {
gaformat93178 Format;
gaformat93178 Mixformat;
NI32 Numsamples;
NI32* Mixbuffer;
gclink93144 Dispatchlist;
gcmutex92270* Dispatchmutex;
gclink93144 Mixlist;
gcmutex92270* Mixmutex;
};
struct  gcmutex92270  {
void* Mutex;
};
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19601)(void);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gc_typesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gc_typesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gc_threadInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gc_threadDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gc_commonInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gc_commonDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gaInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gaDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gauInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gauDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, mainInit)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit)(void);
gaumanager95208* mgr_96009;
extern TY95225 Dl_95224;
gamixer93343* mixer_96014;
extern TY95242 Dl_95241;
extern TFrame* frameptr_16842;

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_gc_typesDatInit();
	HEX00_gc_threadDatInit();
	HEX00_gc_commonDatInit();
	HEX00_gaDatInit();
	HEX00_gauDatInit();
	mainDatInit();
	HEX00_gc_typesInit();
	HEX00_gc_threadInit();
	HEX00_gc_commonInit();
	HEX00_gaInit();
	HEX00_gauInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	mainInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16842;
	frameptr_16842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16842 = (*frameptr_16842).prev;
}
NIM_EXTERNC N_NOINLINE(void, mainInit)(void) {
	nimfr("main", "main.nim")
	nimln(5, "main.nim");
	mgr_96009 = Dl_95224(((NI32) -1), ((NI32) 1), ((NI32) 4), ((NI32) 512));
	nimln(6, "main.nim");
	mixer_96014 = Dl_95241(mgr_96009);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit)(void) {
}

